# Server
quarkus.http.port=8080

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=password
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/patient_admin
quarkus.hibernate-orm.database.generation=update
quarkus.datasource.jdbc.transactions=xa


quarkus.hibernate-orm.schema-management.strategy=drop-and-create
# JWT Config
smallrye.jwt.sign.key.location=config/keys/privateKey.pem
mp.jwt.verify.publickey.location=config/keys/publicKey.pem
mp.jwt.verify.issuer=sunshine-coder-service
#smallrye.jwt.sign.key.location=privateKey.pem
smallrye.jwt.sign.key.algorithm=RS256

# Enable CORS
quarkus.http.cors=true

# Allowed origins
quarkus.http.cors.origins=http://localhost:4200

# Allowed methods
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS

# Allowed headers
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with

# Exposed headers (optional)
quarkus.http.cors.exposed-headers=location,content-disposition

quarkus.transaction-manager.enable-recovery=true